/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#004841",
        "surface-container-highest": "#d9dde0",
        "on-error": "#ffefef",
        "on-tertiary-fixed-variant": "#78001f",
        "outline-variant": "#abadaf",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#ff9198",
        primary: "#4a40e0",
        "on-tertiary": "#ffefef",
        "on-secondary": "#bffff5",
        "surface-container-high": "#dfe3e6",
        "primary-fixed": "#9795ff",
        "on-surface": "#2c2f31",
        "inverse-on-surface": "#9a9d9f",
        "on-primary-fixed-variant": "#1a0099",
        "on-primary-container": "#14007e",
        surface: "#f5f7f9",
        "on-tertiary-fixed": "#39000a",
        "error-container": "#f74b6d",
        "on-secondary-fixed-variant": "#00675e",
        background: "#f5f7f9",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#ff9198",
        "on-background": "#2c2f31",
        "on-secondary-container": "#005c54",
        "surface-variant": "#d9dde0",
        "surface-dim": "#d0d5d8",
        "on-error-container": "#510017",
        "tertiary-fixed-dim": "#ff7984",
        "on-primary": "#f4f1ff",
        "surface-bright": "#f5f7f9",
        "inverse-primary": "#8582ff",
        "error-dim": "#a70138",
        secondary: "#00675e",
        "primary-dim": "#3d30d4",
        tertiary: "#b90035",
        "secondary-fixed": "#89f5e7",
        "tertiary-dim": "#a2002d",
        error: "#b41340",
        "secondary-container": "#89f5e7",
        outline: "#747779",
        "on-surface-variant": "#595c5e",
        "surface-container-low": "#eef1f3",
        "primary-fixed-dim": "#8885ff",
        "primary-container": "#9795ff",
        "on-tertiary-container": "#68001a",
        "surface-tint": "#4a40e0",
        "secondary-dim": "#005a52",
        "secondary-fixed-dim": "#7ae7d8",
        "surface-container": "#e5e9eb",
        "inverse-surface": "#0b0f10",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        glass: "0 12px 40px rgba(44, 47, 49, 0.06)",
        "glass-lg": "0 20px 60px rgba(44, 47, 49, 0.08)",
        primary: "0 8px 20px -4px rgba(74, 64, 224, 0.4)",
      },
      animation: {
        "pulse-ring": "pulseRing 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.6s ease forwards",
        "slide-up": "slideUp 0.5s ease forwards",
        float: "float 3s ease-in-out infinite",
      },
      keyframes: {
        pulseRing: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.3" },
          "50%": { transform: "scale(1.15)", opacity: "0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
